### PR TITLE
Fix old non existing can_send_[sticker...] with can_send_other_messages

### PR DESCRIPTION
**Pull request by DatDraggy**
Fixes https://github.com/pyrogram/pyrogram/issues/698
Introduced by https://github.com/pyrogram/pyrogram/commit/c9d0c5d75a7646b43cd7e8c1f45715fd1630f797

### CODE REVIEW

**Comment by delivrance** [comment]
Not really a bug, this was done on purpose to make permissions look like the ones in official clients for a reason: I noticed that if you set a more granular permissions with the method (I.e. deny gifs/stickers/games & allow inline bots) and open the chat settings with official clients (Android, tdesktop), the permissions will overwrite and will start to apply to all "other" media (I.e. in this example, inline bots become denied as well).

**Comment by DatDraggy** [comment]
Yea I get that, but without this these types would result in `'ChatPermissions' object has no attribute 'can_send_stickers'` because my changes weren't being made. `can_send_stickers` doesn't exist, only `can_send_other_messages` is a thing now.

**Comment by DatDraggy** [comment]
Still relevant. Please take a look at the diff. This implements what you're describing.
